import Link from 'next/link';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { db } from '@/lib/db';
import Header from '@/components/Header';
import { ArrowUpRight,Plus,BookOpen,MessageCircle,ChartNoAxesCombined,Users,FileText,ArrowRight } from 'lucide-react';
export const dynamic='force-dynamic';
export default async function Home(){const session=await getServerSession(authOptions);const userId=(session?.user as {id?:string}|undefined)?.id;let failed=false;
const rooms=userId?await db.room.findMany({where:{participants:{some:{userId}}},include:{_count:{select:{participants:true,documents:true}}},orderBy:{createdAt:'desc'}}).catch(()=>{failed=true;return [];}):[];
return <><Header/><main className="shell"><div className="intro"><div><div className="eyebrow">Make room for understanding</div><h1>Good questions.<br/><em>Better together.</em></h1><p>Your notes, your people, a fresh perspective.<br/>Pull up a chair and work through the difficult bits.</p></div><Link className="button" href={userId?'/rooms/new':'/login'}><Plus size={17}/>Create a study room</Link></div><div className="section-rule"><div className="row"><span className="eyebrow">Your study spaces</span><span className="tag">{rooms.length.toString().padStart(2,'0')}</span></div><span className="muted" style={{fontSize:11}}>A shared table. A clearer head.</span></div>{failed&&<div className="error">We couldn’t load your rooms. Please refresh in a moment.</div>}{rooms.length?<div className="room-grid">{rooms.map((room,i)=><Link href={`/rooms/${room.id}${room.status==='ENDED'?'/summary':''}`} key={room.id} className="room-card"><div><div className="row between"><span className="eyebrow">Room {String(i+1).padStart(2,'0')}</span><span className="tag">{room.status==='ACTIVE'?<><span className="dot"/>Open for study</>:'Rundown ready'}</span></div><h3>{room.name}</h3><p>{room.studyFocusRaw||'A little space to make sense of things.'}</p></div><div className="row between" style={{marginTop:25}}><div className="row muted"><Users size={14}/><small>{room._count.participants}</small><FileText size={14}/><small>{room._count.documents}</small></div><ArrowUpRight size={18} className="accent"/></div></Link>)}</div>:<div className="room-card" style={{padding:'40px',minHeight:230}}><div className="row" style={{gap:28,flexWrap:'wrap'}}><BookOpen size={65} className="accent"/><div><h2>Your next lightbulb moment starts here.</h2><p style={{marginTop:12,maxWidth:520,fontSize:14}}>Bring a chapter, a past paper, or that topic nobody quite gets. Add your friends, and turn “I’m lost” into “I’ve got it.”</p><Link href={userId?'/rooms/new':'/login'} className="row accent" style={{marginTop:22,fontWeight:600}}>{userId?'Set up your first room':'Sign in to get started'}<ArrowRight size={16}/></Link></div></div></div>}<div className="feature-strip"><div><MessageCircle size={26}/><section><h3>Ask. Discuss. Understand.</h3><p>Answers grounded in your course notes, with the exact passages beside them.</p></section></div><div><ChartNoAxesCombined size={26}/><section><h3>How sure are you?</h3><p>A different kind of quiz. Share your real confidence, then learn from the reveal.</p></section></div><div><BookOpen size={26}/><section><h3>Leave with a next step.</h3><p>A thoughtful rundown of what clicked, what didn’t, and where to go next.</p></section></div></div></main></>;}
